// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://nzlvvidtyakkrlmtkgyy.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Im56bHZ2aWR0eWFra3JsbXRrZ3l5Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDUwNjI5NDcsImV4cCI6MjA2MDYzODk0N30.7aZ7gDHrmMpdQt6fBws9blxaKc6WD7dS2PTSN8moXdI";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);